# Generated by Django 4.0 on 2024-02-20 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
