# Generated by Django 4.0 on 2024-02-20 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
